language: node_js

node_js:
  - '6.10'

script:
  - npm run test:ci

after_success:
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info

env:
  global:
    secure: obQmCrl7F6/8OedbmmCD5ebvf3834ChP+Tau6YujQeEdXJ8i3iuzkTTO7TCXUQlYTSD6lZbG3AptN5HgU4luqygYgFUHdmvA83/qjkqgvHzciYfpBNELhgtsTQ/8gl3Fu9ts5NBJQXLS94RZVC/a5fcYBODC5bTHcgFXNjgWlMPSpqjkmNJiWs2gILjwxa6BWX2a1A9olD26vtEKj1l5agRJedpYRYeVK8L1OhDezh4wfz+nTkuFc4870/z2z8Sr7H2si4vBIcGq9RgnsSaUrewAuuZkGiomj3Y+L33E9cIUILtsCJ0AY7jwymYkHXSSWQ8KDiLpQDx4ylAaFVYGM5wFqL334Hpj+nGw5V44vn8lUur7m6s0cqNSHXMwury0CJS4PVMdu/4Yo8D59NAGkOOpo7VyTVnFp3pkfMXCaIiUoQUKPMDHoTIW9wjoq6U9hOPdW9OXMrThOwHyhHO0HdJ1lvGnM33YzPAuw8EJjWKXO6gxpMKPaEHSc6i5MeKwaRxDlLf+vzF7rcm8GJeP0lvzjbihoyuF+bKg8gN3ZpS453UUzghzW3y9/R56Lyib/R2FvKgRusG7gVCtOEWSb2FrG7u9nu/8ywCAZcSVKaHDppqZpqjMi1unAUAQwMLmQYoVfyASkt/WBco481mEEEy2W1RSAcmXwYNicHA91FE=
